---
title: "Jin"
date: "`r Sys.Date()`"
output:
  html_document:
  code_folding: hide
number_sections: false
toc: yes
toc_depth: 3
toc_float: yes
pdf_document:
  toc: yes
toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load necessary libraries
library(devtools)
library(dplyr)
library(ezids)
library(caret)
```

```{r pi}
#load the dataset
df <- read.csv('Fuel Economy Data.csv')
```

```{r modify}

#defining the unwanted columns (columns realted to fuel type 2 and ev)
unwantedlist <- c(
  "barrelsA08",
  "cityA08",
  "cityA08U",
  "co2A",
  "co2TailpipeAGpm",
  "combA08",
  "combA08U",
  "fuelCostA08",
  "fuelType2",
  "highwayA08",
  "highwayA08U",
  "rangeA",
  "rangeCityA",
  "rangeHwyA",
  "UCityA",
  "UHighwayA",
  "charge120",
  "charge240",
  "sCharger",
  "tCharger",
  "c240Dscr",
  "charge240b",
  "c240bDscr",
  "phevHwy",
  "phevCity",
  "phevComb",
  "modifiedOn",
  "cityCD",
  "combinedCD",
  "highwayCD",
  "phevBlended",
  "cityE",
  "combE",
  "combinedUF",
  "evMotor",
  "highwayE",
  "highwayUF",
  "cityUF",
  "rangeCity",
  "rangeHwy",
  "range",
  "hlv",
  "hpv",
  "pv2",
  "pv4",
  "lv2",
  "lv4",
  "comb08U",
  "city08U",
  "highway08U",
  "engId"
)
cleaned_df <- df %>% select(-all_of(unwantedlist))

#considering only from year 2013
cleaned_df <- cleaned_df %>%
  filter(year %in% (2020:2024))

#removing ev vehicles
cleaned_df <- cleaned_df[!is.na(cleaned_df$cylinders) & cleaned_df$cylinders != "Electricity",]
```


```{r}
#check the number of missing values for each column
missing_values <- colSums(is.na(cleaned_df))
missing_values
```


```{r}
#check the number of value 0 for each column
zero_count_per_column <- cleaned_df %>%
  summarise(across(everything(), ~sum(. == 0, na.rm = TRUE)))

zero_count_per_column
```

```{r}
#remove columns that are for car identification
cleaned_df <- cleaned_df %>%
  select(-c(createdOn, mfrCode,
            baseModel,
            model, make, id,
            mpgData))
#remove redundant columns and ghg score and fescore, which would be another dependent variable
cleaned_df <- cleaned_df %>%
  select(-c(co2TailpipeGpm, ghgScore, ghgScoreA, fuelType, feScore))
#remove empty column
cleaned_df <- cleaned_df %>%
  select(-trans_dscr)
```



```{r}
#Identify categorical columns and their unique value counts
categorical_columns <- sapply(cleaned_df, function(col) is.character(col) || is.factor(col))
unique_values <- sapply(cleaned_df[, categorical_columns], function(col) length(unique(col)))

#Separate columns for one-hot and label encoding
one_hot_columns <- names(unique_values[unique_values <= 10]) # Threshold for one-hot encoding
label_columns <- names(unique_values[unique_values > 10])

#Applying One-Hot Encoding
if (length(one_hot_columns) > 0) {
  one_hot_encoded <- dummyVars(~ ., data = cleaned_df[one_hot_columns], fullRank = TRUE)
  one_hot_df <- data.frame(predict(one_hot_encoded, newdata = cleaned_df))
}

#Applying Label Encoding
for (column in label_columns) {
  cleaned_df[[column]] <- as.numeric(as.factor(cleaned_df[[column]]))
}

#Combining one-hot encoded and remaining data
final_data <- bind_cols(cleaned_df %>% select(-one_hot_columns), one_hot_df)

#View the first few rows of the encoded dataset
print(head(final_data))
```

```{r}
#removing categorical variables with two many categories - avoid overfitting
linear_df <- final_data %>%
  select(-c(eng_dscr, trany, VClass))
#remove any mpg because co2 is directly related to mpg (which is tailpipe CO2 in grams/mile)
#also remove barrels08 as it is basically proportional to co2
linear_df <- linear_df %>%
  select(-c(comb08, UCity, UHighway, highway08, city08, barrels08))
```



```{r}
library(leaps)
regfit_full <- regsubsets(co2 ~ ., data = linear_df, nvmax = 35)
reg_summary <- summary(regfit_full)
```


```{r}
# Find the model size using adjusted r squared
best_model_size <- which.max(reg_summary$adjr2)
best_model_size
```

```{r}
#Column names of the best model size
selected_vars <- names(which(reg_summary$which[best_model_size, ])) %>%
  setdiff("(Intercept)")  # Remove intercept

#filter for the column names above
selected_data <- final_data %>%
  select(all_of(selected_vars)) %>%
  mutate(co2 = final_data$co2) #add our dependent variable

```

```{r}
library(car)
library(tidyverse)

#We are going to run VIF to check multicollinearity

vif_model <- lm(co2 ~ ., data = selected_data)

vif_values <- vif(vif_model)

vif_df <- as.data.frame(vif_values) %>%
  rownames_to_column(var = "Variable")
print(vif_df)
```

```{r}
#remove the highest VIF
lm_data <- selected_data %>%
  select(-youSaveSpend)
lm_data <- lm_data %>%
  select(-cylinders)
lm_data <- lm_data %>%
  select(-fuelCost08)

#run vif again
vif_model <- lm(co2 ~ ., data = lm_data)
vif_values <- vif(vif_model)
vif_df <- as.data.frame(vif_values) %>%
  rownames_to_column(var = "Variable")
print(vif_df)
```

```{r}
lm_model <- lm(co2 ~ ., data = lm_data)
summary(lm_model)

```

```{r}
plot(lm_model)
```


```{r}
library(factoextra)
cluster_df <- lm_data

# Elbow method
fviz_nbclust(cluster_df, kmeans, method = "wss") +
    geom_vline(xintercept = 4, linetype = 2)+
  labs(subtitle = "Elbow method")

```

```{r}
# Compute k-means with k = 4
set.seed(123)
scaled_df <- scale(cluster_df)
km_res <- kmeans(scaled_df, 4, nstart = 25)
```



```{r}
# Cluster centers
print(km_res$centers)


```

```{r}
library(ggplot2)

# Add cluster assignments to the original data for visualization
cluster_df$Cluster <- as.factor(km_res$cluster)

# PCA for dimensionality reduction
pca_result <- prcomp(scaled_df)
pca_df <- data.frame(pca_result$x)

# Plotting with ggplot2
ggplot(pca_df, aes(x = PC1, y = PC2, color = cluster_df$Cluster)) +
  geom_point() +
  stat_ellipse(level = 0.95) +  # Add ellipses around clusters (95% confidence intervals)
  labs(title = "K-means Clustering",
       x = "Principal Component 1", y = "Principal Component 2") +
  theme_minimal()
```


```{r}
# Create boxplots for a feature (e.g., engine displacement 'displ') by cluster
ggplot(cluster_df, aes(x = Cluster, y = displ, fill = Cluster)) +
  geom_boxplot() +
  labs(title = "Engine Displacement by Cluster", x = "Cluster", y = "Engine Displacement")
# Create boxplots for a feature (e.g., engine displacement 'displ') by cluster
ggplot(cluster_df, aes(x = Cluster, y = co2, fill = Cluster)) +
  geom_boxplot() +
  labs(title = "Engine Displacement by Cluster", x = "Cluster", y = "Engine Displacement")
```


```{r}
# Calculate the mean of each numeric column grouped by cluster
cluster_means <- cluster_df %>%
  group_by(Cluster) %>%
  summarise(across(where(is.numeric), mean, na.rm = TRUE))

# View the mean of all columns by cluster
xkabledplyhead(cluster_means, 4)
```


```{r}
# ANOVA for 'displ' across clusters
anova_displ <- aov(displ ~ Cluster, data = cluster_df)
summary(anova_displ)

# ANOVA for 'co2' across clusters
anova_co2 <- aov(co2 ~ Cluster, data = cluster_df)
summary(anova_co2)
```


